(() => {
  'use strict';
  const DB='english-hub-v3', STORE='state', LEGACY_KEY='main', SESSION_SIZE=8;
  const PROFILES=[
    {id:'tacio',name:'Tacio'},{id:'marlene',name:'Marlene'},{id:'anny',name:'Anny'},
    {id:'teste-1',name:'Teste 1'},{id:'teste-2',name:'Teste 2'}
  ];
  const STAGES=[
    {id:1,name:'Inglês cotidiano',hint:'Base: rotina, casa, horários e situações sociais'},
    {id:2,name:'Destravar a fala',hint:'Respostas curtas, perguntas e diálogos guiados'},
    {id:3,name:'Quatro competências',hint:'Ouvir, falar, ler e escrever de forma integrada'},
    {id:4,name:'Inglês profissional',hint:'Entrevista, enfermagem, emergência e offshore'},
    {id:5,name:'Independência',hint:'Menos tradução, mais velocidade e automaticidade'}
  ];
  const fresh=()=>({version:4,profileId:null,attempts:[],errors:[],sessions:[],activeSession:null,stage:1,createdAt:new Date().toISOString()});
  let state=fresh(), activeProfile=null, deferredInstall=null, startedAt=0, currentAnswer='', usedHelp=false, confidence=3, recognition=null;
  const $=s=>document.querySelector(s), app=()=>$('#app');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
  const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0, pct=n=>Math.round(n*100), time=n=>n?`${(n/1000).toFixed(1)}s`:'—';
  function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function getKey(key){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function putKey(key,value){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(value,key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
  async function migrateLegacy(){const done=await getKey('profiles:migrated');if(done)return;const old=await getKey(LEGACY_KEY);if(old&&Array.isArray(old.attempts)){const migrated={...fresh(),...old,version:4,profileId:'tacio'};await putKey('profile:tacio',migrated)}await putKey('profiles:migrated',true)}
  async function loadProfile(id){try{await migrateLegacy();activeProfile=PROFILES.find(p=>p.id===id);state={...fresh(),...(await getKey(`profile:${id}`)||{}),profileId:id};$('#storageState').textContent=`✓ Progresso de ${activeProfile.name} salvo neste dispositivo`;dashboard()}catch(e){console.error(e);$('#storageState').textContent='⚠ Armazenamento indisponível'}}
  async function save(){if(activeProfile)await putKey(`profile:${activeProfile.id}`,state)}
  function login(){activeProfile=null;app().innerHTML=`<section class="login"><div class="card"><span class="eyebrow">ESCOLHA QUEM VAI TREINAR</span><h2>Perfis de teste</h2><p class="muted">Cada perfil mantém progresso, erros e sessões separados neste dispositivo.</p><div class="profiles">${PROFILES.map(p=>`<button class="profile" data-id="${p.id}"><span>${p.name.charAt(0)}</span><b>${p.name}</b></button>`).join('')}</div><form id="pinForm" class="pin hidden"><label for="pin">PIN de ${'<b id="pinName"></b>'}</label><input id="pin" type="password" inputmode="numeric" maxlength="4" placeholder="••••" autocomplete="off"><p id="pinError" class="error"></p><div class="tools"><button>ENTRAR</button><button type="button" class="ghost" id="cancelPin">Cancelar</button></div></form><p class="muted small">PIN provisório de todos os perfis: 1234</p></div></section>`;
    let chosen=null;document.querySelectorAll('.profile').forEach(b=>b.onclick=()=>{chosen=b.dataset.id;$('#pinName').textContent=PROFILES.find(p=>p.id===chosen).name;$('#pinForm').classList.remove('hidden');$('#pin').focus()});$('#cancelPin').onclick=()=>{$('#pinForm').classList.add('hidden');chosen=null};$('#pinForm').onsubmit=async e=>{e.preventDefault();if($('#pin').value!=='1234'){ $('#pinError').textContent='PIN incorreto. Tente 1234.';return }await loadProfile(chosen)};
  }
  function attemptsFor(skill){return state.attempts.filter(a=>a.skill===skill)}
  function metric(skill){const a=attemptsFor(skill);if(!a.length)return{accuracy:0,mastery:0,automaticity:0,responseTime:0};const recent=a.slice(-12),accuracy=avg(recent.map(x=>x.accuracy)),speed=avg(recent.map(x=>Math.max(0,1-x.responseTime/45000))),independence=avg(recent.map(x=>x.independence)),conf=avg(recent.map(x=>x.confidence/5));return{accuracy,mastery:.55*accuracy+.25*independence+.2*conf,automaticity:.45*accuracy+.35*speed+.2*independence,responseTime:avg(recent.map(x=>x.responseTime))}}
  function stageProgress(){const skills=['listening','speaking','reading','writing'];const mastery=avg(skills.map(s=>metric(s).mastery));const sessions=state.sessions.length;let stage=1;if(sessions>=2&&mastery>=.35)stage=2;if(sessions>=5&&mastery>=.5)stage=3;if(sessions>=9&&mastery>=.62)stage=4;if(sessions>=14&&mastery>=.75)stage=5;state.stage=Math.max(state.stage||1,stage);return {stage:state.stage,mastery}}
  function dashboard(){const skills=['listening','speaking','reading','writing'],labels={listening:'Listening',speaking:'Speaking',reading:'Reading',writing:'Writing'},auto=avg(skills.map(s=>metric(s).automaticity)),last=state.sessions.slice(-5).reverse(),sp=stageProgress(),stage=STAGES[sp.stage-1];
    app().innerHTML=`<section class="profilebar"><div><span class="muted">Perfil ativo</span><b>${esc(activeProfile.name)}</b></div><button class="ghost" id="switch">Trocar usuário</button></section><section class="hero"><div class="card"><span class="eyebrow">ETAPA ${stage.id} DE 5 · ${stage.name.toUpperCase()}</span><h2>Treine para responder<br><span class="accent">sem traduzir.</span></h2><p class="muted">${stage.hint}. As sessões sempre combinam Listening, Speaking, Reading e Writing.</p><button id="train">${state.activeSession?'CONTINUAR TREINO':'TREINAR AGORA'}</button></div><div class="card stage-card"><span class="muted">Automaticidade geral</span><strong class="giant">${pct(auto)}%</strong><div class="bar"><i style="width:${pct(auto)}%"></i></div><p class="muted">${state.attempts.length} respostas · ${state.errors.length} erros registrados</p></div></section><div class="metrics">${skills.map(s=>metricCard(labels[s],metric(s).mastery)).join('')}${metricCard('Automaticidade',auto)}</div><div class="section-title"><h3>Jornada de aprendizagem</h3><span class="muted">Etapa atual: ${stage.id}/5</span></div><div class="journey">${STAGES.map(s=>`<div class="journey-step ${s.id<stage.id?'done':s.id===stage.id?'active':''}"><b>${s.id}. ${s.name}</b><span>${s.id<stage.id?'Concluída':s.id===stage.id?'Em andamento':'Bloqueada'}</span></div>`).join('')}</div><div class="section-title"><h3>Histórico recente</h3><span class="muted">${state.sessions.length} sessões</span></div><div class="history">${last.length?last.map(s=>`<div class="history-row"><span>${new Date(s.endedAt).toLocaleDateString('pt-BR')} · ${s.count} atividades</span><b>${pct(s.accuracy)}% acerto</b><span>${time(s.avgTime)}</span><span>${pct(s.automaticity)}% automático</span></div>`).join(''):'<div class="card muted">O primeiro resumo aparecerá aqui.</div>'}</div><div class="section-title"><h3>Privacidade e teste</h3></div><div class="card"><p>O progresso de ${esc(activeProfile.name)} fica separado no IndexedDB deste navegador.</p><button class="ghost danger" id="reset">Apagar progresso deste perfil</button></div>`;
    $('#train').onclick=()=>state.activeSession?showExercise():startSession();$('#reset').onclick=reset;$('#switch').onclick=login;save();
  }
  function metricCard(name,value){return `<div class="card metric"><span class="muted">${name}</span><strong>${pct(value)}%</strong><div class="bar"><i style="width:${pct(value)}%"></i></div></div>`}
  function allowedExercise(ex){const stage=state.stage||1;if(stage<=2)return ex.stage<=stage;if(stage===3)return ex.stage<=3;return ex.stage<=stage}
  function weakness(ex){const m=metric(ex.skill),domainErrors=state.errors.filter(e=>e.domain===ex.domain).length,last=state.attempts.filter(a=>a.exerciseId===ex.id).slice(-1)[0];let review=0;if(last&&last.accuracy<.7){const age=Date.now()-new Date(last.at).getTime();review=age>86400000?2.2:1.2}return(1-m.mastery)*4+domainErrors*.15+(last?-.5:1)+review+Math.random()*.2}
  function buildQueue(){const required=['listening','speaking','reading','writing'];let selected=[];required.forEach(skill=>{const pool=EXERCISES.filter(x=>x.skill===skill&&allowedExercise(x)).sort((a,b)=>weakness(b)-weakness(a));selected.push(...pool.slice(0,2))});return selected.slice(0,SESSION_SIZE).sort((a,b)=>required.indexOf(a.skill)-required.indexOf(b.skill)).map(x=>x.id)}
  async function startSession(){state.activeSession={id:crypto.randomUUID?.()||String(Date.now()),queue:buildQueue(),index:0,attemptIds:[],startedAt:new Date().toISOString()};await save();showExercise()}
  function current(){return EXERCISES.find(x=>x.id===state.activeSession.queue[state.activeSession.index])}
  function showExercise(){const ex=current();if(!ex)return finish();currentAnswer='';usedHelp=false;confidence=3;startedAt=performance.now();const idx=state.activeSession.index;app().innerHTML=`<section class="session"><div class="session-head"><span>${esc(activeProfile.name)} · Etapa ${state.stage}</span><button class="ghost" id="exit">Salvar e sair</button></div><div class="progress">${state.activeSession.queue.map((_,i)=>`<i class="${i<idx?'done':''}"></i>`).join('')}</div><div class="card"><span class="skill-tag">${icon(ex.skill)} ${ex.skill} · ${ex.domain}</span><div class="prompt">${esc(ex.prompt||ex.text||'Ouça e responda:')}</div>${ex.audio?`<div class="tools"><button class="audio-btn" id="play">▶ OUVIR ÁUDIO</button><button class="ghost" id="replay">Ouvir novamente</button></div>`:''}${ex.choices.length?`<div class="choice-list">${ex.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div>`:`<textarea class="answer" id="answer" placeholder="${ex.skill==='speaking'?'Fale ou digite sua resposta em inglês…':'Digite sua resposta em inglês…'}"></textarea>${ex.skill==='speaking'?`<div class="tools"><button class="speak-btn" id="speak">● COMEÇAR A FALAR</button><span id="speechStatus" class="muted"></span></div>`:''}`}<label class="checkbox"><input type="checkbox" id="help"> Usei tradução, dica ou ajuda externa</label><label class="muted">Confiança: <input id="confidence" type="range" min="1" max="5" value="3"> <b id="confidenceValue">3/5</b></label><div class="tools"><button id="check" disabled>CORRIGIR</button></div></div></section>`;
    if(ex.audio){$('#play').onclick=()=>speakText(ex.audio);$('#replay').onclick=()=>{usedHelp=true;speakText(ex.audio)}}document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');currentAnswer=b.dataset.value;$('#check').disabled=false});if($('#answer'))$('#answer').oninput=e=>{currentAnswer=e.target.value;$('#check').disabled=!currentAnswer.trim()};if($('#speak'))$('#speak').onclick=startRecognition;$('#help').onchange=e=>usedHelp=e.target.checked;$('#confidence').oninput=e=>{$('#confidenceValue').textContent=`${e.target.value}/5`;confidence=+e.target.value};$('#check').onclick=()=>check(ex);$('#exit').onclick=()=>{save();dashboard()};
  }
  function scoreText(input,ex){const n=norm(input),target=norm(ex.answer),keys=ex.keywords.map(norm),hits=keys.filter(k=>n.includes(k)).length,keyScore=keys.length?hits/keys.length:0,targetWords=new Set(target.split(' ')),words=n.split(' ').filter(Boolean),overlap=words.filter(w=>targetWords.has(w)).length/Math.max(targetWords.size,1);return Math.min(1,.75*keyScore+.25*overlap)}
  async function check(ex){const elapsed=Math.round(performance.now()-startedAt),accuracy=ex.choices.length?(norm(currentAnswer)===norm(ex.answer)?1:0):scoreText(currentAnswer,ex),independence=usedHelp?.55:1,speed=Math.max(0,1-elapsed/45000),mastery=.55*accuracy+.25*independence+.2*(confidence/5),automaticity=.45*accuracy+.35*speed+.2*independence,attempt={id:crypto.randomUUID?.()||String(Date.now()),exerciseId:ex.id,stage:state.stage,skill:ex.skill,domain:ex.domain,answer:currentAnswer,expected:ex.answer,accuracy,responseTime:elapsed,independence,mastery,confidence,automaticity,at:new Date().toISOString()};state.attempts.push(attempt);state.activeSession.attemptIds.push(attempt.id);if(accuracy<.7)state.errors.push({...attempt,errorId:attempt.id});const weak=accuracy<.7;if(weak){const review=EXERCISES.filter(x=>x.skill===ex.skill&&x.domain===ex.domain&&x.id!==ex.id&&allowedExercise(x)).sort((a,b)=>weakness(b)-weakness(a))[0];if(review&&!state.activeSession.queue.slice(state.activeSession.index+1).includes(review.id))state.activeSession.queue.splice(Math.min(state.activeSession.index+3,state.activeSession.queue.length),0,review.id)}await save();const card=document.querySelector('.session .card');card.innerHTML+=`<div class="feedback ${weak?'bad':''}"><b>${weak?'Ainda não consolidado':'Boa resposta'}</b><p>Sua resposta: ${esc(currentAnswer)}</p><p>Modelo: <strong>${esc(ex.answer)}</strong></p><div class="score-grid"><span>Acerto <b>${pct(accuracy)}%</b></span><span>Tempo <b>${time(elapsed)}</b></span><span>Automaticidade <b>${pct(automaticity)}%</b></span></div>${weak?'<p class="muted">Uma revisão relacionada foi inserida nesta sessão.</p>':''}</div><button id="next">PRÓXIMA ATIVIDADE</button>`;$('#check').disabled=true;$('#next').onclick=async()=>{state.activeSession.index++;await save();showExercise()}}
  async function finish(){const ids=state.activeSession.attemptIds,a=state.attempts.filter(x=>ids.includes(x.id)),summary={id:state.activeSession.id,endedAt:new Date().toISOString(),count:a.length,accuracy:avg(a.map(x=>x.accuracy)),avgTime:avg(a.map(x=>x.responseTime)),automaticity:avg(a.map(x=>x.automaticity))};state.sessions.push(summary);state.activeSession=null;stageProgress();await save();app().innerHTML=`<section class="session"><div class="card summary"><span class="eyebrow">SESSÃO CONCLUÍDA · ${esc(activeProfile.name)}</span><div class="big">${pct(summary.accuracy)}%</div><h2>Precisão da sessão</h2><div class="score-grid"><div class="card"><span class="muted">Tempo médio</span><h3>${time(summary.avgTime)}</h3></div><div class="card"><span class="muted">Automaticidade</span><h3>${pct(summary.automaticity)}%</h3></div><div class="card"><span class="muted">Atividades</span><h3>${summary.count}</h3></div></div><p class="muted">O próximo treino priorizará competências e temas com menor domínio.</p><button id="home">VER DASHBOARD</button></div></section>`;$('#home').onclick=dashboard}
  function speakText(text){if(!('speechSynthesis'in window))return alert('Áudio não disponível neste navegador.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}
  function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#speechStatus').textContent='Reconhecimento não suportado; digite a resposta.';return}recognition=new SR();recognition.lang='en-US';recognition.interimResults=true;recognition.onstart=()=>{$('#speechStatus').textContent='Ouvindo…';$('#speak').textContent='■ PARAR'};recognition.onresult=e=>{currentAnswer=Array.from(e.results).map(r=>r[0].transcript).join(' ');$('#answer').value=currentAnswer;$('#check').disabled=!currentAnswer};recognition.onerror=e=>$('#speechStatus').textContent=`Não foi possível ouvir (${e.error}).`;recognition.onend=()=>{$('#speechStatus').textContent=currentAnswer?'Fala registrada.':'Toque para tentar novamente.';$('#speak').textContent='● COMEÇAR A FALAR'};recognition.start()}
  function icon(s){return({listening:'◉',speaking:'●',reading:'▤',writing:'✎'})[s]}
  async function reset(){if(!confirm(`Apagar todo o progresso de ${activeProfile.name}?`))return;state={...fresh(),profileId:activeProfile.id};await save();dashboard()}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')}};
  async function init(){login();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error)}init();
})();
