(() => {
  'use strict';
  const DB='english-hub-v3', STORE='state', KEY='main', SESSION_SIZE=8;
  const initial={version:3,attempts:[],errors:[],sessions:[],skillStats:{},activeSession:null,createdAt:new Date().toISOString()};
  let state=structuredClone(initial), deferredInstall=null, startedAt=0, currentAnswer='', usedHelp=false, confidence=3, recognition=null;
  const $=s=>document.querySelector(s), app=()=>$('#app');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
  function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
  async function load(){try{const db=await dbOpen(), saved=await new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(saved)state={...structuredClone(initial),...saved};$('#storageState').textContent='✓ Progresso salvo no dispositivo'}catch(e){$('#storageState').textContent='⚠ Armazenamento indisponível';console.error(e)}}
  async function save(){try{const db=await dbOpen();await new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(state,KEY);r.onsuccess=res;r.onerror=()=>rej(r.error)})}catch(e){console.error(e)}}
  function attemptsFor(skill){return state.attempts.filter(a=>a.skill===skill)}
  function metric(skill){const a=attemptsFor(skill);if(!a.length)return{accuracy:0,mastery:0,automaticity:0,responseTime:0};const recent=a.slice(-12), accuracy=avg(recent.map(x=>x.accuracy)), speed=avg(recent.map(x=>Math.max(0,1-x.responseTime/45000))), independence=avg(recent.map(x=>x.independence)), confidence=avg(recent.map(x=>x.confidence/5)), mastery=.55*accuracy+.25*independence+.2*confidence;return{accuracy,mastery,automaticity:.45*accuracy+.35*speed+.2*independence,responseTime:avg(recent.map(x=>x.responseTime))}}
  const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0, pct=n=>Math.round(n*100), time=n=>n?`${(n/1000).toFixed(1)}s`:'—';
  function dashboard(){
    const skills=['listening','speaking','reading','writing'], labels={listening:'Listening',speaking:'Speaking',reading:'Reading',writing:'Writing'};
    const auto=avg(skills.map(s=>metric(s).automaticity)), last=state.sessions.slice(-5).reverse();
    app().innerHTML=`<section class="hero"><div class="card"><span class="eyebrow">TREINO ADAPTATIVO LOCAL</span><h2>Treine para responder<br><span class="accent">sem traduzir.</span></h2><p class="muted">Sessões curtas que combinam ouvir, falar, ler e escrever conforme seu desempenho.</p><button id="train">${state.activeSession?'CONTINUAR TREINO':'TREINAR AGORA'}</button></div><div class="card"><span class="muted">Automaticidade geral</span><strong style="font-size:4rem;display:block">${pct(auto)}%</strong><div class="bar"><i style="width:${pct(auto)}%"></i></div><p class="muted">${state.attempts.length} respostas · ${state.errors.length} erros registrados</p></div></section>
    <div class="metrics">${skills.map(s=>metricCard(labels[s],metric(s).mastery)).join('')}${metricCard('Automaticidade',auto)}</div>
    <div class="section-title"><h3>Histórico recente</h3><span class="muted">${state.sessions.length} sessões</span></div><div class="history">${last.length?last.map(s=>`<div class="history-row"><span>${new Date(s.endedAt).toLocaleDateString('pt-BR')} · ${s.count} atividades</span><b>${pct(s.accuracy)}% acerto</b><span>${time(s.avgTime)}</span><span>${pct(s.automaticity)}% automático</span></div>`).join(''):'<div class="card muted">Seu primeiro resumo aparecerá aqui.</div>'}</div>
    <div class="section-title"><h3>Privacidade e teste</h3></div><div class="card"><p>O progresso fica no IndexedDB deste navegador. Feche e reabra o app para validar a continuidade.</p><button class="ghost danger" id="reset">Apagar progresso</button></div>`;
    $('#train').onclick=()=>state.activeSession?showExercise():startSession();$('#reset').onclick=reset;
  }
  function metricCard(name,value){const v=typeof value==='number'?value:value.mastery;return `<div class="card metric"><span class="muted">${name}</span><strong>${pct(v)}%</strong><div class="bar"><i style="width:${pct(v)}%"></i></div></div>`}
  function weakness(ex){const m=metric(ex.skill), domainErrors=state.errors.filter(e=>e.domain===ex.domain).length;return (1-m.mastery)*4+domainErrors*.15+(state.attempts.some(a=>a.exerciseId===ex.id)?-.7:1)+Math.random()*.35}
  function buildQueue(){const required=['listening','speaking','reading','writing'];let selected=[];required.forEach(skill=>{const pool=EXERCISES.filter(x=>x.skill===skill).sort((a,b)=>weakness(b)-weakness(a));selected.push(...pool.slice(0,2))});return selected.sort((a,b)=>required.indexOf(a.skill)-required.indexOf(b.skill)).map(x=>x.id)}
  async function startSession(){state.activeSession={id:crypto.randomUUID?.()||String(Date.now()),queue:buildQueue(),index:0,attemptIds:[],startedAt:new Date().toISOString()};await save();showExercise()}
  function current(){return EXERCISES.find(x=>x.id===state.activeSession.queue[state.activeSession.index])}
  function showExercise(){const ex=current();if(!ex)return finish();currentAnswer='';usedHelp=false;confidence=3;startedAt=performance.now();const idx=state.activeSession.index;
    app().innerHTML=`<section class="session"><div class="progress">${state.activeSession.queue.map((_,i)=>`<i class="${i<idx?'done':''}"></i>`).join('')}</div><div class="card"><span class="skill-tag">${icon(ex.skill)} ${ex.skill} · ${ex.domain}</span><div class="prompt">${esc(ex.prompt||ex.text||'Ouça e responda:')}</div>${ex.audio?`<div class="tools"><button class="audio-btn" id="play">▶ OUVIR ÁUDIO</button><button class="ghost" id="replay">Ouvir novamente</button></div>`:''}${ex.choices.length?`<div class="choice-list">${ex.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div>`:`<textarea class="answer" id="answer" placeholder="${ex.skill==='speaking'?'Fale ou digite sua resposta em inglês…':'Digite sua resposta em inglês…'}"></textarea>${ex.skill==='speaking'?`<div class="tools"><button class="speak-btn" id="speak">● COMEÇAR A FALAR</button><span id="speechStatus" class="muted"></span></div>`:''}`}<label class="checkbox"><input type="checkbox" id="help"> Usei tradução, dica ou ajuda externa</label><label class="muted">Confiança: <input id="confidence" type="range" min="1" max="5" value="3"> <b id="confidenceValue">3/5</b></label><div class="tools"><button id="check" disabled>CORRIGIR</button><button class="ghost" id="exit">Salvar e sair</button></div></div></section>`;
    if(ex.audio){$('#play').onclick=()=>speakText(ex.audio);$('#replay').onclick=()=>{usedHelp=true;speakText(ex.audio)}}
    document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{document.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');currentAnswer=b.dataset.value;$('#check').disabled=false});
    if($('#answer'))$('#answer').oninput=e=>{currentAnswer=e.target.value;$('#check').disabled=!currentAnswer.trim()};
    if($('#speak'))$('#speak').onclick=()=>startRecognition();$('#help').onchange=e=>usedHelp=e.target.checked;$('#confidence').oninput=e=>{$('#confidenceValue').textContent=`${e.target.value}/5`;confidence=+e.target.value};$('#check').onclick=()=>check(ex);$('#exit').onclick=()=>{save();dashboard()};
  }
  function scoreText(input,ex){const n=norm(input), target=norm(ex.answer), keys=ex.keywords.map(norm), hits=keys.filter(k=>n.includes(k)).length;const keyScore=keys.length?hits/keys.length:0;const targetWords=new Set(target.split(' ')), words=n.split(' ').filter(Boolean), overlap=words.filter(w=>targetWords.has(w)).length/Math.max(targetWords.size,1);return Math.min(1,.75*keyScore+.25*overlap)}
  async function check(ex){const elapsed=Math.round(performance.now()-startedAt), accuracy=ex.choices.length?(norm(currentAnswer)===norm(ex.answer)?1:0):scoreText(currentAnswer,ex), independence=usedHelp?.55:1, speed=Math.max(0,1-elapsed/45000), mastery=.55*accuracy+.25*independence+.2*(confidence/5), automaticity=.45*accuracy+.35*speed+.2*independence;
    const attempt={id:crypto.randomUUID?.()||String(Date.now()),exerciseId:ex.id,skill:ex.skill,domain:ex.domain,answer:currentAnswer,expected:ex.answer,accuracy,responseTime:elapsed,independence,mastery,confidence,automaticity,at:new Date().toISOString()};state.attempts.push(attempt);state.activeSession.attemptIds.push(attempt.id);if(accuracy<.7)state.errors.push({...attempt,errorId:attempt.id});
    const weak=accuracy<.7;if(weak){const review=EXERCISES.filter(x=>x.skill===ex.skill&&x.domain===ex.domain&&x.id!==ex.id).sort((a,b)=>weakness(b)-weakness(a))[0];if(review&&!state.activeSession.queue.slice(state.activeSession.index+1).includes(review.id))state.activeSession.queue.splice(Math.min(state.activeSession.index+3,state.activeSession.queue.length),0,review.id)}await save();
    const card=document.querySelector('.session .card');card.innerHTML+=`<div class="feedback ${weak?'bad':''}"><b>${weak?'Ainda não consolidado':'Boa resposta'}</b><p>Sua resposta: ${esc(currentAnswer)}</p><p>Modelo: <strong>${esc(ex.answer)}</strong></p><div class="score-grid"><span>Acerto <b>${pct(accuracy)}%</b></span><span>Tempo <b>${time(elapsed)}</b></span><span>Automaticidade <b>${pct(automaticity)}%</b></span></div>${weak?'<p class="muted">Uma revisão relacionada foi inserida nesta sessão.</p>':''}</div><button id="next">PRÓXIMA ATIVIDADE</button>`;$('#check').disabled=true;$('#next').onclick=async()=>{state.activeSession.index++;await save();showExercise()};
  }
  async function finish(){const ids=state.activeSession.attemptIds,a=state.attempts.filter(x=>ids.includes(x.id)),summary={id:state.activeSession.id,endedAt:new Date().toISOString(),count:a.length,accuracy:avg(a.map(x=>x.accuracy)),avgTime:avg(a.map(x=>x.responseTime)),automaticity:avg(a.map(x=>x.automaticity))};state.sessions.push(summary);state.activeSession=null;await save();app().innerHTML=`<section class="session"><div class="card summary"><span class="eyebrow">SESSÃO CONCLUÍDA</span><div class="big">${pct(summary.accuracy)}%</div><h2>Precisão da sessão</h2><div class="score-grid"><div class="card"><span class="muted">Tempo médio</span><h3>${time(summary.avgTime)}</h3></div><div class="card"><span class="muted">Automaticidade</span><h3>${pct(summary.automaticity)}%</h3></div><div class="card"><span class="muted">Atividades</span><h3>${summary.count}</h3></div></div><p class="muted">Seu próximo treino priorizará competências e temas com menor domínio.</p><button id="home">VER DASHBOARD</button></div></section>`;$('#home').onclick=dashboard}
  function speakText(text){if(!('speechSynthesis'in window))return alert('Áudio não disponível neste navegador.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.88;speechSynthesis.speak(u)}
  function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('#speechStatus').textContent='Reconhecimento não suportado; digite a resposta.';return}recognition=new SR();recognition.lang='en-US';recognition.interimResults=true;recognition.onstart=()=>{$('#speechStatus').textContent='Ouvindo…';$('#speak').textContent='■ PARAR'};recognition.onresult=e=>{currentAnswer=Array.from(e.results).map(r=>r[0].transcript).join(' ');$('#answer').value=currentAnswer;$('#check').disabled=!currentAnswer};recognition.onerror=e=>$('#speechStatus').textContent=`Não foi possível ouvir (${e.error}).`;recognition.onend=()=>{$('#speechStatus').textContent=currentAnswer?'Fala registrada.':'Toque para tentar novamente.';$('#speak').textContent='● COMEÇAR A FALAR'};recognition.start()}
  function icon(s){return({listening:'◉',speaking:'●',reading:'▤',writing:'✎'})[s]}
  async function reset(){if(!confirm('Apagar todo o histórico deste dispositivo?'))return;state=structuredClone(initial);await save();dashboard()}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').classList.add('hidden')}};
  async function init(){await load();dashboard();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error)}init();
})();
