window.EXERCISES = (() => {
  const raw = [
  ['L01','listening','general','A2','I need to leave early today.','O que a pessoa precisa fazer?',['Sair cedo hoje','Chegar tarde amanhã','Ficar em casa'],'Sair cedo hoje',['leave early']],
  ['L02','listening','general','A2','Could you repeat that more slowly, please?','Qual é o pedido?',['Repetir mais devagar','Falar mais alto','Escrever um e-mail'],'Repetir mais devagar',['repeat','slowly']],
  ['L03','listening','clinical','B1','The patient reports chest pain that started twenty minutes ago.','Quando a dor começou?',['Há 20 minutos','Ontem','Há 2 horas'],'Há 20 minutos',['twenty minutes']],
  ['L04','listening','clinical','B1','Please check the patient’s blood pressure and oxygen saturation.','Quais medidas foram solicitadas?',['Pressão e saturação','Temperatura e glicemia','Pulso e dor'],'Pressão e saturação',['blood pressure','oxygen saturation']],
  ['L05','listening','emergency','B1','We have an unconscious adult with no normal breathing. Start CPR now.','Qual é a conduta imediata?',['Iniciar RCP','Aguardar exames','Oferecer água'],'Iniciar RCP',['start cpr']],
  ['L06','listening','emergency','B1','The motorcycle rider has severe bleeding from the left leg.','Onde está o sangramento?',['Perna esquerda','Braço direito','Tórax'],'Perna esquerda',['left leg']],
  ['L07','listening','interview','B1','Tell me about a difficult decision you made at work.','O recrutador pede um exemplo de quê?',['Decisão difícil','Curso recente','Pretensão salarial'],'Decisão difícil',['difficult decision']],
  ['L08','listening','interview','B1','Why do you want to work in an offshore environment?','Qual tema deve ser respondido?',['Motivação para offshore','Endereço residencial','Folgas anteriores'],'Motivação para offshore',['why','offshore']],
  ['L09','listening','offshore','B1','The medevac helicopter is expected to arrive in fifteen minutes.','Em quanto tempo chega o helicóptero?',['15 minutos','50 minutos','5 minutos'],'15 minutos',['fifteen minutes']],
  ['L10','listening','offshore','B1','All personnel must report to the muster station immediately.','Para onde todos devem ir?',['Ponto de encontro','Enfermaria','Heliponto'],'Ponto de encontro',['muster station']],
  ['L11','listening','clinical','B1','The patient is allergic to penicillin and shellfish.','Quais alergias foram informadas?',['Penicilina e frutos do mar','Látex e dipirona','Iodo e amendoim'],'Penicilina e frutos do mar',['penicillin','shellfish']],
  ['L12','listening','offshore','B1','Gas was detected near the pump room. Do not enter the area.','Qual orientação foi dada?',['Não entrar na área','Desligar o rádio','Ir buscar ferramentas'],'Não entrar na área',['do not enter']],
  ['S01','speaking','general','A2','Diga em inglês: “Eu verifico primeiro os sinais vitais do paciente.”',null,[],'I assess the patient’s vital signs first.',['assess','patient','vital signs','first']],
  ['S02','speaking','general','A2','Responda: “How are you feeling today?”',null,[],'I am feeling well today.',['feeling','today']],
  ['S03','speaking','clinical','B1','Pergunte ao paciente onde dói.',null,[],'Where does it hurt?',['where','hurt']],
  ['S04','speaking','clinical','B1','Peça ao paciente para respirar fundo.',null,[],'Please take a deep breath.',['please','deep breath']],
  ['S05','speaking','emergency','B1','Informe que você vai controlar o sangramento.',null,[],'I am going to control the bleeding.',['control','bleeding']],
  ['S06','speaking','emergency','B1','Diga: “Precisamos de uma ambulância imediatamente.”',null,[],'We need an ambulance immediately.',['need','ambulance','immediately']],
  ['S07','speaking','interview','B1','Apresente-se em uma frase profissional.',null,[],'I am an emergency nurse with extensive experience in urgent care.',['emergency nurse','experience']],
  ['S08','speaking','interview','B1','Explique brevemente seu ponto forte: calma sob pressão.',null,[],'My main strength is staying calm under pressure.',['strength','calm','pressure']],
  ['S09','speaking','offshore','B1','Confirme que o kit de emergência está completo.',null,[],'The emergency kit is complete and ready.',['emergency kit','complete','ready']],
  ['S10','speaking','offshore','B1','Solicite evacuação médica.',null,[],'We need to arrange a medical evacuation.',['medical evacuation']],
  ['S11','speaking','clinical','B1','Oriente: “Não coma nem beba até a avaliação médica.”',null,[],'Do not eat or drink until the medical assessment.',['not','eat','drink','assessment']],
  ['S12','speaking','offshore','B1','Relate que o trabalhador está consciente e estável.',null,[],'The worker is conscious and stable.',['worker','conscious','stable']],
  ['R01','reading','general','A2','The meeting was postponed until Friday.','Quando será a reunião?',['Sexta-feira','Segunda-feira','Hoje'],'Sexta-feira',['friday']],
  ['R02','reading','general','A2','Maria missed the bus, so she called a taxi.','Por que Maria chamou um táxi?',['Perdeu o ônibus','Estava chovendo','O carro quebrou'],'Perdeu o ônibus',['missed the bus']],
  ['R03','reading','clinical','B1','The medication must be administered after checking the patient’s identity and prescription.','O que deve ser verificado antes?',['Identidade e prescrição','Apenas o leito','Somente a temperatura'],'Identidade e prescrição',['identity','prescription']],
  ['R04','reading','clinical','B1','The wound is red, warm, swollen, and draining yellow fluid.','Qual achado sugere infecção?',['Secreção amarela','Pele fria','Ausência de edema'],'Secreção amarela',['yellow fluid']],
  ['R05','reading','emergency','B1','A patient with facial droop, arm weakness, and slurred speech requires immediate stroke assessment.','Qual protocolo é prioritário?',['AVC','Sepse','Trauma abdominal'],'AVC',['stroke']],
  ['R06','reading','emergency','B1','Do not remove an impaled object. Stabilize it and control bleeding around it.','O que fazer com o objeto?',['Estabilizá-lo','Removê-lo rápido','Empurrá-lo'],'Estabilizá-lo',['stabilize']],
  ['R07','reading','interview','B1','Candidates must hold valid offshore safety certificates and be available for a 14-by-14 rotation.','Qual disponibilidade é exigida?',['Escala 14x14','Somente fins de semana','Horário comercial'],'Escala 14x14',['14-by-14']],
  ['R08','reading','interview','B1','The role requires accurate records, teamwork, and clear communication in emergencies.','Qual competência NÃO foi citada?',['Programação','Trabalho em equipe','Comunicação clara'],'Programação',['records','teamwork','communication']],
  ['R09','reading','offshore','B1','During a general alarm, stop work, make the area safe, and proceed to your assigned muster station.','Qual é o último passo descrito?',['Ir ao ponto de encontro','Iniciar o trabalho','Chamar a família'],'Ir ao ponto de encontro',['muster station']],
  ['R10','reading','offshore','B1','The clinic inventory must include controlled-drug records, expiry dates, and minimum stock levels.','O que deve constar no inventário?',['Registros, validades e estoque mínimo','Só nome do medicamento','Somente preço'],'Registros, validades e estoque mínimo',['expiry dates','stock']],
  ['R11','reading','clinical','B1','Before discharge, confirm that the patient understands warning signs and follow-up instructions.','O que confirmar antes da alta?',['Compreensão das orientações','A cor da roupa','A profissão do acompanhante'],'Compreensão das orientações',['understands','warning signs']],
  ['R12','reading','offshore','B1','A confined-space rescue must not begin until the hazards are assessed and the rescue plan is activated.','O que precede o resgate?',['Avaliar riscos e ativar o plano','Entrar imediatamente','Desligar toda comunicação'],'Avaliar riscos e ativar o plano',['hazards','rescue plan']],
  ['W01','writing','general','A2','Escreva em inglês: “Preciso de mais tempo.”',null,[],'I need more time.',['need','more time']],
  ['W02','writing','general','A2','Escreva uma frase dizendo que você chegará às oito.',null,[],'I will arrive at eight.',['arrive','eight']],
  ['W03','writing','clinical','B1','Registre em inglês: paciente alerta e orientado.',null,[],'The patient is alert and oriented.',['patient','alert','oriented']],
  ['W04','writing','clinical','B1','Escreva uma orientação para manter o curativo limpo e seco.',null,[],'Keep the dressing clean and dry.',['dressing','clean','dry']],
  ['W05','writing','emergency','B1','Registre: dor torácica, intensidade 8/10, início súbito.',null,[],'Chest pain rated eight out of ten with sudden onset.',['chest pain','eight','sudden onset']],
  ['W06','writing','emergency','B1','Escreva: oxigênio iniciado por máscara.',null,[],'Oxygen was started by face mask.',['oxygen','mask']],
  ['W07','writing','interview','B1','Responda em uma frase por que devemos contratá-lo.',null,[],'You should hire me because I combine emergency experience with occupational health knowledge.',['hire','emergency','occupational health']],
  ['W08','writing','interview','B1','Escreva uma frase sobre trabalho em equipe sob pressão.',null,[],'I communicate clearly and support my team under pressure.',['communicate','team','pressure']],
  ['W09','writing','offshore','B1','Registre que o caso foi discutido com o médico em terra.',null,[],'The case was discussed with the onshore doctor.',['case','onshore doctor']],
  ['W10','writing','offshore','B1','Escreva que os sinais vitais serão reavaliados em 15 minutos.',null,[],'Vital signs will be reassessed in fifteen minutes.',['vital signs','reassessed','fifteen minutes']],
  ['W11','writing','clinical','B1','Registre que não foram observadas reações adversas.',null,[],'No adverse reactions were observed.',['no','adverse reactions','observed']],
  ['W12','writing','offshore','B1','Escreva uma passagem de caso informando que o trabalhador permanece estável.',null,[],'The worker remains stable and will continue under observation.',['worker','stable','observation']],
  ['L13','listening','emergency','B1','Administer oxygen and prepare the defibrillator.','Quais duas ações foram solicitadas?',['Oxigênio e desfibrilador','Soro e curativo','Glicemia e transporte'],'Oxigênio e desfibrilador',['oxygen','defibrillator']],
  ['S13','speaking','interview','B1','Diga que possui certificações offshore válidas.',null,[],'I hold valid offshore safety certifications.',['valid','offshore','certifications']]
  ];
  return raw.map(([id,skill,domain,level,audioOrText,prompt,choices,answer,keywords]) => ({id,skill,domain,level,audio:skill==='listening'?audioOrText:null,text:skill==='listening'?null:audioOrText,prompt,choices,answer,keywords}));
})();
