(() => {
  'use strict';
  const unit=(id,level,title,domain,grammar,goal,patterns)=>({id,level,title,domain,grammar,goal,patterns});
  window.CURRICULUM_UNITS_B=[
    unit('B1-U01','B1','Narrativas e sequências','narratives','past simple; past continuous; sequencing','Contar histórias com contexto e sequência clara',[
      ['I was {} when the phone rang.','Eu estava {} quando o telefone tocou.',[['driving home','dirigindo para casa'],['preparing dinner','preparando o jantar'],['talking to my neighbor','conversando com meu vizinho'],['waiting for the bus','esperando o ônibus']]],
      ['By the time we arrived, {}.','Quando chegamos, {}.',[['the store had closed','a loja já tinha fechado'],['the meeting had started','a reunião já tinha começado'],['everyone had left','todos já tinham ido embora'],['the rain had stopped','a chuva já tinha parado']]],
      ['At first, I thought {}.','No início, achei que {}.',[['it was a mistake','era um engano'],['the task would be easy','a tarefa seria fácil'],['we were in the wrong place','estávamos no lugar errado'],['nothing had changed','nada tinha mudado']]],
      ['After that, we decided to {}.','Depois disso, decidimos {}.',[['ask for help','pedir ajuda'],['change our route','mudar nosso trajeto'],['wait until morning','esperar até de manhã'],['call the manager','ligar para o gerente']]],
      ['In the end, {}.','No final, {}.',[['everything worked out','tudo deu certo'],['we found a solution','encontramos uma solução'],['the event was canceled','o evento foi cancelado'],['I learned an important lesson','aprendi uma lição importante']]]
    ]),
    unit('B1-U02','B1','Opiniões e justificativas','opinions','opinion clauses; because; although','Expressar e sustentar opiniões pessoais',[
      ['In my opinion, {}.','Na minha opinião, {}.',[['the course is well organized','o curso é bem organizado'],['public transport should improve','o transporte público deveria melhorar'],['practice matters more than talent','a prática importa mais do que o talento'],['this option is more realistic','esta opção é mais realista']]],
      ['I agree because {}.','Eu concordo porque {}.',[['the evidence is clear','as evidências são claras'],['it would save time','isso economizaria tempo'],['everyone would benefit','todos se beneficiariam'],['the current system is confusing','o sistema atual é confuso']]],
      ['Although {}, I still think it is worthwhile.','Embora {}, ainda acho que vale a pena.',[['it may be expensive','possa ser caro'],['the process takes time','o processo leve tempo'],['there are some risks','existam alguns riscos'],['not everyone agrees','nem todos concordem']]],
      ['The main reason is that {}.','A principal razão é que {}.',[['we need better results','precisamos de resultados melhores'],['people learn differently','as pessoas aprendem de formas diferentes'],['the situation has changed','a situação mudou'],['quality is more important than speed','qualidade é mais importante do que velocidade']]],
      ['From my point of view, we should {}.','Do meu ponto de vista, deveríamos {}.',[['consider another option','considerar outra opção'],['listen to both sides','ouvir os dois lados'],['focus on the long term','focar no longo prazo'],['test the idea first','testar a ideia primeiro']]]
    ]),
    unit('B1-U03','B1','Condições e consequências','conditions','first and second conditionals; unless','Explicar condições reais e hipotéticas',[
      ['If we {}, we will finish on time.','Se nós {}, terminaremos no prazo.',[['start now','começarmos agora'],['share the work','dividirmos o trabalho'],['follow the plan','seguirmos o plano'],['avoid interruptions','evitarmos interrupções']]],
      ['If I had more time, I would {}.','Se eu tivesse mais tempo, eu {}.',[['study another language','estudaria outro idioma'],['exercise every day','me exercitaria todos os dias'],['travel more often','viajaria com mais frequência'],['volunteer in my community','faria trabalho voluntário na minha comunidade']]],
      ['Unless you {}, the problem may continue.','A menos que você {}, o problema pode continuar.',[['change the settings','mude as configurações'],['talk to the manager','fale com o gerente'],['follow the instructions','siga as instruções'],['ask for professional help','peça ajuda profissional']]],
      ['What would you do if {}?','O que você faria se {}?',[['you lost your phone','perdesse seu telefone'],['the plan suddenly changed','o plano mudasse de repente'],['you had to choose today','tivesse que escolher hoje'],['a friend asked for advice','um amigo pedisse conselho']]],
      ['As long as {}, we can continue.','Desde que {}, podemos continuar.',[['everyone agrees','todos concordem'],['the weather stays calm','o tempo continue calmo'],['we have enough time','tenhamos tempo suficiente'],['the results remain positive','os resultados continuem positivos']]]
    ]),
    unit('B1-U04','B1','Metas e progresso','goals','present perfect; future forms; purpose','Definir metas e acompanhar progresso',[
      ['I have been working on {} for three months.','Estou trabalhando em {} há três meses.',[['my pronunciation','minha pronúncia'],['a personal project','um projeto pessoal'],['a healthier routine','uma rotina mais saudável'],['my communication skills','minhas habilidades de comunicação']]],
      ['My next goal is to {}.','Minha próxima meta é {}.',[['speak with more confidence','falar com mais confiança'],['complete the course','concluir o curso'],['apply for a new position','me candidatar a uma nova vaga'],['manage my time better','administrar melhor meu tempo']]],
      ['So far, I have {}.','Até agora, eu {}.',[['made steady progress','fiz progresso constante'],['completed half the plan','concluí metade do plano'],['overcome several difficulties','superei várias dificuldades'],['learned from my mistakes','aprendi com meus erros']]],
      ['I am doing this in order to {}.','Estou fazendo isso para {}.',[['improve my future opportunities','melhorar minhas oportunidades futuras'],['feel more independent','me sentir mais independente'],['communicate more clearly','me comunicar com mais clareza'],['build a consistent habit','criar um hábito consistente']]],
      ['By the end of the year, I hope to {}.','Até o fim do ano, espero {}.',[['reach the next level','alcançar o próximo nível'],['save enough money','economizar dinheiro suficiente'],['finish my main project','terminar meu projeto principal'],['feel comfortable speaking','me sentir confortável falando']]]
    ]),
    unit('B1-U05','B1','Solução de problemas','problem-solving','modals; suggestions; cause and solution','Analisar problemas e propor ações',[
      ['The problem seems to be {}.','O problema parece ser {}.',[['a lack of communication','falta de comunicação'],['an incorrect setting','uma configuração incorreta'],['a delay in the process','um atraso no processo'],['conflicting information','informações conflitantes']]],
      ['One possible solution would be to {}.','Uma solução possível seria {}.',[['restart the system','reiniciar o sistema'],['divide the task into steps','dividir a tarefa em etapas'],['speak to everyone involved','falar com todos os envolvidos'],['try a different approach','tentar uma abordagem diferente']]],
      ['We could prevent this by {}.','Poderíamos evitar isso {}.',[['checking everything in advance','verificando tudo com antecedência'],['setting clearer expectations','definindo expectativas mais claras'],['keeping a written record','mantendo um registro escrito'],['reviewing the process regularly','revisando o processo regularmente']]],
      ['The situation may get worse unless we {}.','A situação pode piorar a menos que nós {}.',[['act quickly','ajamos rapidamente'],['identify the cause','identifiquemos a causa'],['change the schedule','mudemos o cronograma'],['ask for additional support','peçamos apoio adicional']]],
      ['Let us compare the options before we {}.','Vamos comparar as opções antes de {}.',[['make a final decision','tomar uma decisão final'],['spend more money','gastar mais dinheiro'],['change the entire plan','mudar o plano inteiro'],['inform the rest of the team','informar o restante da equipe']]]
    ]),
    unit('B1-U06','B1','Mídia e tecnologia','technology','passives; relative clauses; reporting','Explicar usos, benefícios e riscos da tecnologia',[
      ['This app is used to {}.','Este aplicativo é usado para {}.',[['track daily habits','acompanhar hábitos diários'],['organize shared tasks','organizar tarefas compartilhadas'],['practice pronunciation','praticar pronúncia'],['store important documents','armazenar documentos importantes']]],
      ['The device that I bought {}.','O aparelho que comprei {}.',[['works better than expected','funciona melhor do que eu esperava'],['needs a software update','precisa de uma atualização de software'],['came with clear instructions','veio com instruções claras'],['has already stopped working','já parou de funcionar']]],
      ['According to the article, {}.','Segundo o artigo, {}.',[['screen time is increasing','o tempo de tela está aumentando'],['privacy remains a concern','a privacidade continua sendo uma preocupação'],['remote work is becoming common','o trabalho remoto está se tornando comum'],['the results are still uncertain','os resultados ainda são incertos']]],
      ['My data may be shared if I {}.','Meus dados podem ser compartilhados se eu {}.',[['accept these conditions','aceitar estas condições'],['use a public network','usar uma rede pública'],['connect another service','conectar outro serviço'],['change the privacy settings','mudar as configurações de privacidade']]],
      ['Technology makes it easier to {}, but it can also be distracting.','A tecnologia facilita {}, mas também pode causar distração.',[['stay in touch','manter contato'],['learn independently','aprender de forma independente'],['work from anywhere','trabalhar de qualquer lugar'],['access information quickly','acessar informações rapidamente']]]
    ]),
    unit('B1-U07','B1','Relações e cultura','culture','relative clauses; used to; contrast','Descrever relações, costumes e diferenças culturais',[
      ['I used to {}, but now I prefer something different.','Eu costumava {}, mas agora prefiro algo diferente.',[['live in a small town','morar em uma cidade pequena'],['spend every weekend at home','passar todo fim de semana em casa'],['avoid speaking in public','evitar falar em público'],['work a traditional schedule','trabalhar em um horário tradicional']]],
      ['A close friend is someone who {}.','Um amigo próximo é alguém que {}.',[['listens without judging','escuta sem julgar'],['keeps their promises','cumpre suas promessas'],['supports you in difficult times','apoia você em momentos difíceis'],['tells you the truth','diz a verdade a você']]],
      ['In my culture, it is common to {}.','Na minha cultura, é comum {}.',[['greet people warmly','cumprimentar as pessoas calorosamente'],['share food with visitors','compartilhar comida com visitantes'],['stay close to the family','manter proximidade com a família'],['celebrate important dates together','celebrar datas importantes juntos']]],
      ['Unlike my hometown, this city {}.','Ao contrário da minha cidade natal, esta cidade {}.',[['never seems to sleep','parece nunca dormir'],['has excellent public transport','tem um excelente transporte público'],['offers many cultural events','oferece muitos eventos culturais'],['feels less personal','parece menos pessoal']]],
      ['It took me a while to get used to {}.','Levei um tempo para me acostumar com {}.',[['the local accent','o sotaque local'],['the colder weather','o clima mais frio'],['a different daily rhythm','um ritmo diário diferente'],['meeting people from many backgrounds','conhecer pessoas de muitas origens']]]
    ]),
    unit('B1-U08','B1','Estudo e colaboração','collaboration','reported speech; task language; feedback','Colaborar, reportar e dar feedback construtivo',[
      ['She said that she would {}.','Ela disse que iria {}.',[['send the file later','enviar o arquivo mais tarde'],['review my notes','revisar minhas anotações'],['join the next meeting','participar da próxima reunião'],['explain the new process','explicar o novo processo']]],
      ['Could you clarify what you mean by {}?','Você poderia esclarecer o que quer dizer com {}?',[['better results','resultados melhores'],['the final version','a versão final'],['shared responsibility','responsabilidade compartilhada'],['a more practical approach','uma abordagem mais prática']]],
      ['I suggest that we {} first.','Sugiro que nós {} primeiro.',[['define the main objective','definamos o objetivo principal'],['review the available information','revisemos as informações disponíveis'],['assign each person a task','atribuamos uma tarefa a cada pessoa'],['test a smaller version','testemos uma versão menor']]],
      ['Your explanation was clear, although {}.','Sua explicação foi clara, embora {}.',[['one example was missing','faltasse um exemplo'],['the conclusion was too brief','a conclusão fosse breve demais'],['some terms were unfamiliar','alguns termos fossem desconhecidos'],['the main point came late','o ponto principal aparecesse tarde']]],
      ['Let me summarize what we have agreed: {}.','Deixe-me resumir o que combinamos: {}.',[['we will meet again on Friday','vamos nos reunir novamente na sexta-feira'],['each person will complete one section','cada pessoa concluirá uma seção'],['the first draft is due tomorrow','a primeira versão vence amanhã'],['we will review the results together','revisaremos os resultados juntos']]]
    ]),
    unit('B2-U01','B2','Opiniões com nuance','nuanced-opinions','hedging; concession; stance','Defender posições com cautela e precisão',[
      ['To some extent, I agree that {}, although the issue is more complex.','Até certo ponto, concordo que {}, embora a questão seja mais complexa.',[['technology improves access','a tecnologia melhora o acesso'],['competition encourages progress','a competição estimula o progresso'],['rules create consistency','as regras criam consistência'],['experience matters most','a experiência é o que mais importa']]],
      ['It could be argued that {}.','Pode-se argumentar que {}.',[['the benefits outweigh the risks','os benefícios superam os riscos'],['the policy needs to be revised','a política precisa ser revisada'],['individual choices affect everyone','escolhas individuais afetam todos'],['the results depend on context','os resultados dependem do contexto']]],
      ['I am not entirely convinced that {}.','Não estou totalmente convencido de que {}.',[['this is the only solution','esta seja a única solução'],['the change will reduce costs','a mudança vá reduzir custos'],['the evidence is strong enough','as evidências sejam fortes o suficiente'],['everyone would support the proposal','todos apoiariam a proposta']]],
      ['While I understand the concern, {}.','Embora eu entenda a preocupação, {}.',[['we should examine the facts first','deveríamos examinar os fatos primeiro'],['the alternative may be worse','a alternativa pode ser pior'],['a gradual change seems reasonable','uma mudança gradual parece razoável'],['we cannot ignore the long-term impact','não podemos ignorar o impacto de longo prazo']]],
      ['My view is based largely on {}.','Minha opinião se baseia principalmente em {}.',[['personal experience','experiência pessoal'],['the available evidence','evidências disponíveis'],['conversations with other people','conversas com outras pessoas'],['the results of previous attempts','resultados de tentativas anteriores']]]
    ]),
    unit('B2-U02','B2','Hipóteses e especulação','speculation','mixed conditionals; modal deduction','Avaliar possibilidades e resultados alternativos',[
      ['If we had acted earlier, {} might not have happened.','Se tivéssemos agido antes, {} talvez não tivesse acontecido.',[['the delay','o atraso'],['the misunderstanding','o mal-entendido'],['the additional expense','a despesa adicional'],['the loss of information','a perda de informação']]],
      ['She must have {} because she knows every detail.','Ela deve ter {} porque conhece cada detalhe.',[['read the full report','lido o relatório completo'],['attended the earlier meeting','participado da reunião anterior'],['spoken directly to the manager','falado diretamente com o gerente'],['followed the case closely','acompanhado o caso de perto']]],
      ['The change could have been caused by {}.','A mudança pode ter sido causada por {}.',[['a technical failure','uma falha técnica'],['unexpected demand','uma demanda inesperada'],['a difference in methodology','uma diferença de metodologia'],['incomplete information','informações incompletas']]],
      ['Suppose that {}, how would we respond?','Suponha que {}; como responderíamos?',[['the budget were cut in half','o orçamento fosse reduzido pela metade'],['the deadline were moved forward','o prazo fosse antecipado'],['the main supplier withdrew','o principal fornecedor desistisse'],['the initial results proved wrong','os resultados iniciais se mostrassem errados']]],
      ['Had I known about {}, I would have prepared differently.','Se eu soubesse de {}, teria me preparado de outra forma.',[['the schedule change','a mudança de horário'],['the additional requirement','a exigência adicional'],['the traffic disruption','a interrupção no trânsito'],['the level of difficulty','o nível de dificuldade']]]
    ]),
    unit('B2-U03','B2','Causa, efeito e tendências','cause-effect','complex connectors; trend language','Explicar relações de causa, efeito e evolução',[
      ['The increase was largely due to {}.','O aumento ocorreu principalmente devido a {}.',[['higher demand','uma demanda maior'],['changes in behavior','mudanças de comportamento'],['a shortage of alternatives','uma escassez de alternativas'],['improved data collection','uma coleta de dados melhor']]],
      ['As a result of {}, the organization changed its approach.','Como resultado de {}, a organização mudou sua abordagem.',[['public feedback','opiniões do público'],['unexpected costs','custos inesperados'],['new evidence','novas evidências'],['rapid growth','crescimento rápido']]],
      ['The trend is likely to continue, provided that {}.','A tendência provavelmente continuará, desde que {}.',[['conditions remain stable','as condições permaneçam estáveis'],['investment does not decline','o investimento não diminua'],['people maintain these habits','as pessoas mantenham esses hábitos'],['the policy is fully implemented','a política seja totalmente implementada']]],
      ['One consequence that is often overlooked is {}.','Uma consequência frequentemente ignorada é {}.',[['the effect on small communities','o efeito sobre pequenas comunidades'],['the loss of personal contact','a perda de contato pessoal'],['the pressure on existing services','a pressão sobre serviços existentes'],['the growing need for training','a necessidade crescente de treinamento']]],
      ['The figures suggest a gradual shift toward {}.','Os números sugerem uma mudança gradual em direção a {}.',[['remote services','serviços remotos'],['more flexible schedules','horários mais flexíveis'],['preventive action','ações preventivas'],['independent learning','aprendizagem independente']]]
    ]),
    unit('B2-U04','B2','Negociação e consenso','negotiation','diplomatic language; conditionals; compromise','Negociar prioridades e construir acordos',[
      ['We would be prepared to {} provided that you {}.','Estaríamos dispostos a {}, desde que vocês {}.',[['extend the deadline','ampliar o prazo'],['confirm the new schedule','confirmem o novo cronograma'],['reduce the initial scope','reduzir o escopo inicial'],['protect the core requirements','protejam os requisitos centrais'],['share the additional cost','dividir o custo adicional'],['guarantee technical support','garantam suporte técnico'],['approve a trial period','aprovar um período de teste'],['provide regular feedback','forneçam feedback regular']]],
      ['Our main concern is {}, rather than {}.','Nossa principal preocupação é {}, e não {}.',[['long-term reliability','confiabilidade no longo prazo'],['short-term convenience','conveniência imediata'],['the quality of the outcome','a qualidade do resultado'],['the speed of delivery','a velocidade da entrega'],['clear responsibility','responsabilidade clara'],['the number of participants','o número de participantes'],['fair access','acesso justo'],['temporary savings','economia temporária']]],
      ['Would it be possible to {} without {}?','Seria possível {} sem {}?',[['simplify the process','simplificar o processo'],['removing essential checks','remover verificações essenciais'],['adjust the schedule','ajustar o cronograma'],['increasing the total cost','aumentar o custo total'],['test the proposal','testar a proposta'],['disrupting current work','interromper o trabalho atual'],['share the data','compartilhar os dados'],['compromising privacy','comprometer a privacidade']]],
      ['A reasonable compromise might be to {}.','Um acordo razoável poderia ser {}.',[['begin with a smaller group','começar com um grupo menor'],['review the decision after a month','revisar a decisão após um mês'],['keep the current system temporarily','manter o sistema atual temporariamente'],['divide the resources more evenly','dividir os recursos de forma mais equilibrada']]],
      ['Before we commit, we need clarification regarding {}.','Antes de nos comprometermos, precisamos de esclarecimentos sobre {}.',[['the final cost','o custo final'],['who will be responsible','quem será responsável'],['how progress will be measured','como o progresso será medido'],['what happens if the plan fails','o que acontece se o plano falhar']]]
    ]),
    unit('B2-U05','B2','Comunicação formal','formal-communication','formal register; passives; nominalization','Produzir mensagens formais claras e adequadas',[
      ['I am writing to request {}.','Escrevo para solicitar {}.',[['further information about the program','mais informações sobre o programa'],['confirmation of my appointment','confirmação da minha consulta'],['a review of the decision','uma revisão da decisão'],['access to the relevant documents','acesso aos documentos relevantes']]],
      ['Please be advised that {}.','Informamos que {}.',[['the schedule has been revised','o cronograma foi revisado'],['additional identification is required','é necessária identificação adicional'],['the office will remain closed','o escritório permanecerá fechado'],['your request has been approved','sua solicitação foi aprovada']]],
      ['I would appreciate it if you could {}.','Agradeceria se você pudesse {}.',[['respond at your earliest convenience','responder assim que possível'],['clarify the next steps','esclarecer os próximos passos'],['forward this message to the appropriate person','encaminhar esta mensagem à pessoa adequada'],['confirm receipt of the attached file','confirmar o recebimento do arquivo anexado']]],
      ['The purpose of this message is to {}.','O objetivo desta mensagem é {}.',[['summarize our recent discussion','resumir nossa conversa recente'],['address a recurring concern','tratar de uma preocupação recorrente'],['propose a change to the procedure','propor uma mudança no procedimento'],['document the agreed actions','documentar as ações acordadas']]],
      ['Should you require {}, please contact me.','Caso necessite de {}, entre em contato comigo.',[['any additional information','qualquer informação adicional'],['support with the process','apoio com o processo'],['a copy of the original document','uma cópia do documento original'],['clarification on any point','esclarecimento sobre qualquer ponto']]]
    ]),
    unit('B2-U06','B2','Leitura crítica da mídia','critical-media','reporting verbs; source evaluation; contrast','Avaliar fontes, argumentos e evidências',[
      ['The author claims that {}, but provides limited evidence.','O autor afirma que {}, mas apresenta poucas evidências.',[['the method is completely reliable','o método é totalmente confiável'],['the change benefits everyone','a mudança beneficia todos'],['the trend will continue indefinitely','a tendência continuará indefinidamente'],['the problem has been solved','o problema foi resolvido']]],
      ['The report fails to distinguish between {} and {}.','O relatório não faz distinção entre {} e {}.',[['correlation','correlação'],['causation','causalidade'],['personal opinion','opinião pessoal'],['verified fact','fato verificado'],['short-term change','mudança de curto prazo'],['long-term trend','tendência de longo prazo'],['average results','resultados médios'],['individual cases','casos individuais']]],
      ['This source appears credible because {}.','Esta fonte parece confiável porque {}.',[['the methodology is explained','a metodologia é explicada'],['the data can be checked','os dados podem ser verificados'],['several experts are cited','vários especialistas são citados'],['limitations are acknowledged','as limitações são reconhecidas']]],
      ['A different interpretation of the data would be that {}.','Uma interpretação diferente dos dados seria que {}.',[['other factors influenced the result','outros fatores influenciaram o resultado'],['the change is only temporary','a mudança é apenas temporária'],['the sample was not representative','a amostra não foi representativa'],['expectations affected the responses','as expectativas afetaram as respostas']]],
      ['Before sharing the story, we should verify {}.','Antes de compartilhar a notícia, deveríamos verificar {}.',[['who published it','quem a publicou'],['when the event occurred','quando o evento ocorreu'],['whether the quotation is complete','se a citação está completa'],['what the original source says','o que diz a fonte original']]]
    ]),
    unit('B2-U07','B2','Experiências complexas','complex-experiences','perfect aspects; reflection; emphasis','Relatar experiências e refletir sobre aprendizados',[
      ['Looking back, I realize that {}.','Olhando para trás, percebo que {}.',[['I underestimated the challenge','subestimei o desafio'],['the experience changed my priorities','a experiência mudou minhas prioridades'],['small decisions made a difference','pequenas decisões fizeram diferença'],['I should have asked for help sooner','deveria ter pedido ajuda antes']]],
      ['What I found most difficult was {}.','O que achei mais difícil foi {}.',[['dealing with uncertainty','lidar com a incerteza'],['adapting to constant change','me adaptar a mudanças constantes'],['expressing complex ideas clearly','expressar ideias complexas com clareza'],['maintaining confidence under pressure','manter a confiança sob pressão']]],
      ['I had never {} until that point.','Eu nunca tinha {} até aquele momento.',[['questioned that assumption','questionado aquela suposição'],['worked with such a diverse group','trabalhado com um grupo tão diverso'],['faced a decision of that scale','enfrentado uma decisão daquela dimensão'],['understood the issue so deeply','compreendido a questão tão profundamente']]],
      ['The experience taught me the importance of {}.','A experiência me ensinou a importância de {}.',[['preparing for alternatives','me preparar para alternativas'],['listening before reacting','ouvir antes de reagir'],['communicating expectations clearly','comunicar expectativas com clareza'],['reviewing decisions honestly','revisar decisões com honestidade']]],
      ['Had it not been for {}, I might have given up.','Se não fosse por {}, talvez eu tivesse desistido.',[['the support of my family','o apoio da minha família'],['a clear sense of purpose','um propósito claro'],['the progress I had already made','o progresso que eu já tinha feito'],['encouragement from my teacher','o incentivo da minha professora']]]
    ]),
    unit('B2-U08','B2','Debate e decisões','debate','argument structure; rebuttal; synthesis','Comparar argumentos e chegar a decisões fundamentadas',[
      ['The strongest argument in favor of {} is {}.','O argumento mais forte a favor de {} é {}.',[['the proposal','a proposta'],['its potential long-term benefit','seu possível benefício de longo prazo'],['the new system','o novo sistema'],['its greater transparency','sua maior transparência'],['the investment','o investimento'],['the opportunity it creates','a oportunidade que ele cria'],['the restriction','a restrição'],['the protection it provides','a proteção que ela oferece']]],
      ['Opponents point out that {}, whereas supporters emphasize {}.','Os opositores apontam que {}, enquanto os apoiadores enfatizam {}.',[['the cost is high','o custo é alto'],['the expected return','o retorno esperado'],['implementation will be difficult','a implementação será difícil'],['the need for change','a necessidade de mudança'],['access may be unequal','o acesso pode ser desigual'],['the wider social benefit','o benefício social mais amplo'],['results are uncertain','os resultados são incertos'],['the risk of doing nothing','o risco de não fazer nada']]],
      ['That argument overlooks the fact that {}.','Esse argumento ignora o fato de que {}.',[['circumstances have changed','as circunstâncias mudaram'],['not everyone has the same resources','nem todos têm os mesmos recursos'],['the evidence is still incomplete','as evidências ainda estão incompletas'],['short-term costs may prevent larger losses','custos de curto prazo podem evitar perdas maiores']]],
      ['On balance, the most sensible option is to {}.','Considerando tudo, a opção mais sensata é {}.',[['run a limited trial','realizar um teste limitado'],['gather more reliable data','reunir dados mais confiáveis'],['combine elements of both proposals','combinar elementos das duas propostas'],['delay the decision until the risks are clearer','adiar a decisão até que os riscos estejam mais claros']]],
      ['Any final decision should take into account {}.','Qualquer decisão final deve levar em conta {}.',[['the people most affected','as pessoas mais afetadas'],['both immediate and future costs','os custos imediatos e futuros'],['the quality of the available evidence','a qualidade das evidências disponíveis'],['whether the outcome can be reversed','se o resultado pode ser revertido']]]
    ])
  ];
})();
